only: issues
exemptProjects: true
exemptMilestones: true
daysUntilStale: 20
daysUntilClose: 180
exemptLabels:
    - Priority
    - Backlog
staleLabel: "PR Welcome"
markComment: >
    Thanks a lot for reporting the issue.
    We did not consider the issue as "Priority" or "Backlog",
    so we're not going to work on that anytime soon.
    Please create a pull request to fix the issue if this is a bug report.
    We'll then review it as quickly as possible.
    If you're interested in contributing a feature, please contact us
    first here before creating a pull request. We'll then decide whether
    we'd accept it or not.
    Thanks for your understanding.
closeComment: >
    Closed due to inactivity (180 days).
    Please feel free to continue the discussion or provide the missing information on this issue,
    we'll then reopen it if necessary.
    Thanks a lot!