image: tetraweb/php:7.1

stages:
  - docs

cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
    - ~/.composer/cache

before_script:
  - docker-php-ext-enable zip opcache

docs:
  stage: docs
  when: always
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    expire_in: 1 week
    paths:
      - documentation
  script:
    - .ci/setup-docs.sh
    - .ci/run-docs.sh
    # move to root as we don't want to have subdirectories in build artifact
    - rm -rf documentation && mv tmp-docs/pimcore-docs/build/static documentation
