image: tetraweb/php:7.1

stages:
  - docs

cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
    - ~/.composer/cache

before_script:
  - docker-php-ext-enable zip opcache

docs:
  stage: docs
  when: always
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    expire_in: 1 week
    paths:
      - documentation
  script:
    - rm -rf tmp documentation
    - git clone https://github.com/pimcore/pimcore-docs.git tmp/pimcore-docs
    - cd tmp/pimcore-docs
    - LATEST_VERSION=$(git describe --abbrev=0)
    - echo "Checking out latest pimcore-docs version ${LATEST_VERSION}"
    - git checkout ${LATEST_VERSION}
    - composer install
    - bin/console prepare -c 4.x.x ../../docs
    - bin/console generate
    - mv build/static ../../documentation
