notifications:
  email:
    - travis-ci@pimcore.org

sudo: false
language: php

php:
  - 7.1
  - 7.2
  - 7.3

services:
  - redis

addons:
  mariadb: '10.3'
  hosts:
    - pimcore-test.dev

matrix:
  include:
    - os: linux
      sudo: required
      php: 7.1
      env:
          - PIMCORE_TEST_SUITE=rest
          - PIMCORE_TEST_ENV=http
    - os: linux
      sudo: required
      php: 7.2
      env:
          - PIMCORE_TEST_SUITE=rest
          - PIMCORE_TEST_ENV=http
    - os: linux
      sudo: required
      php: 7.3
      env:
          - PIMCORE_TEST_SUITE=rest
          - PIMCORE_TEST_ENV=http
    - os: linux
      php: 7.1
      env:
          - PIMCORE_TEST_SUITE=cache
          - PIMCORE_TEST_GROUP=cache.core.redis
          - PIMCORE_TEST_SETUP_SKIP_PHP_REDIS_EXTENSION=true
    - os: linux
      php: 7.1
      services: ~
      addons: ~
      env:
        - TASK_TESTS=0
        - TASK_DOCS=1
      cache:
        directories:
          - tmp-docs/pimcore-docs/vendor

cache:
  directories:
    - $HOME/.cache/composer

env:
  global:
    - TASK_TESTS=1
    - TASK_DOCS=0
    - PIMCORE_ENVIRONMENT=test
    - PIMCORE_TEST=1
    - PIMCORE_TEST_URL=http://pimcore-test.dev
    - PIMCORE_TEST_DB_DSN="mysql://root@localhost/pimcore_test"
    - PIMCORE_TEST_CACHE_REDIS_DATABASE=1

before_install:
  - mysql --version
  - mysql -e "CREATE DATABASE pimcore_test CHARSET=utf8mb4;"

install:
  - if [ $TASK_TESTS == 1 ]; then .travis/setup-tests.sh; fi
  - if [ $TASK_DOCS == 1 ]; then .ci/setup-docs.sh; fi

before_script:
  - phpenv config-rm xdebug.ini
  - if [ $TASK_TESTS == 1 ]; then .travis/setup-php.sh; fi
  - if [ $TASK_TESTS == 1 ]; then .travis/setup-functional-tests.sh; fi

script:
  - if [ $TASK_TESTS == 1 ]; then .travis/run-tests.sh; fi
  - if [ $TASK_DOCS == 1 ]; then .ci/run-docs.sh; fi
