notifications:
  email:
    - travis-ci@pimcore.org

sudo: false
language: php

services:
  - redis

addons:
  mariadb: '10.1'
  hosts:
    - pimcore-test.dev

matrix:
  include:
    # Symfony 3.4 all tests
    - os: linux
      sudo: required
      php: 7.2

    - os: linux
      sudo: required
      php: 7.3

    # Symfony 4.* all tests
    - os: linux
      sudo: required
      php: 7.2
      env:
        - SYMFONY_VERSION="^4.0"

    - os: linux
      sudo: required
      php: 7.3
      env:
        - SYMFONY_VERSION="^4.0"

    # Other Tests
    - os: linux
      sudo: required
      php: 7.2
      env:
          - PIMCORE_TEST_SUITE=rest
          - PIMCORE_TEST_ENV=http

    - os: linux
      sudo: required
      php: 7.3
      env:
          - PIMCORE_TEST_SUITE=rest
          - PIMCORE_TEST_ENV=http

    - os: linux
      php: 7.2
      env:
          - PIMCORE_TEST_SUITE=cache
          - PIMCORE_TEST_GROUP=cache.core.redis
          - PIMCORE_TEST_SETUP_SKIP_PHP_REDIS_EXTENSION=true

    # Test Stan
    - os: linux
      php: 7.2
      env:
        - TASK_TESTS=0
        - TASK_STAN=1
    - os: linux
      php: 7.3
      env:
        - TASK_TESTS=0
        - TASK_STAN=1

    # Test Stan Symfony ^4.0
    - os: linux
      php: 7.2
      env:
        - TASK_TESTS=0
        - TASK_STAN=1
        - SYMFONY_VERSION="^4.0"
    - os: linux
      php: 7.3
      env:
        - TASK_TESTS=0
        - TASK_STAN=1
        - SYMFONY_VERSION="^4.0"

    # Test Docs
    - os: linux
      php: 7.2
      services: ~
      addons: ~
      env:
        - TASK_TESTS=0
        - TASK_DOCS=1
      cache:
        directories:
          - tmp-docs/pimcore-docs/vendor
  allow_failures:
    - env:
        - TASK_TESTS=0
        - TASK_STAN=1
    - env:
        - TASK_TESTS=0
        - TASK_STAN=1
        - SYMFONY_VERSION="^4.0"
  fast_finish: true

cache:
  directories:
    - $HOME/.cache/composer

env:
  global:
    - COMPOSER_MEMORY_LIMIT=-1
    - TASK_TESTS=1
    - TASK_STAN=0
    - TASK_DOCS=0
    - PIMCORE_ENVIRONMENT=test
    - PIMCORE_TEST=1
    - PIMCORE_TEST_URL=http://pimcore-test.dev
    - PIMCORE_TEST_DB_DSN="mysql://root@localhost/pimcore_test"
    - PIMCORE_TEST_CACHE_REDIS_DATABASE=1
    - SYMFONY_VERSION=^3.4
    - PIMCORE_PROJECT_ROOT=$TRAVIS_BUILD_DIR

before_install:
  - mysql --version
  - mysql -e "SET GLOBAL innodb_file_format=Barracuda;"
  - mysql -e "SET GLOBAL innodb_large_prefix=1;"
  - mysql -e "CREATE DATABASE pimcore_test CHARSET=utf8mb4;"

install:
  - if [ $TASK_TESTS == 1 ]; then .travis/setup-tests.sh; fi
  - if [ $TASK_STAN == 1 ]; then .travis/setup-tests.sh; fi
  - if [ $TASK_DOCS == 1 ]; then .travis/setup-docs.sh; fi


before_script:
  - phpenv config-rm xdebug.ini
  - if [ $TASK_TESTS == 1 ]; then .travis/setup-php.sh; fi
  - if [ $TASK_TESTS == 1 ]; then .travis/setup-functional-tests.sh; fi
  - if [ $TASK_STAN == 1 ]; then .travis/setup-php.sh; fi

script:
  - if [ $TASK_TESTS == 1 ]; then .travis/run-tests.sh; fi
  - if [ $TASK_DOCS == 1 ]; then .travis/run-docs.sh; fi
  - if [ $TASK_STAN == 1 ]; then .travis/run-stan.sh; fi
