# see https://docs.travis-ci.com/user/customizing-the-build/

notifications:
  email:
    - travis-ci@pimcore.org

branches:
  only:
    - master
    - /^v?\d+\..*/
    - /.*_travis$/

sudo: false
language: php

services:
  - redis
  - mysql

# see https://docs.travis-ci.com/user/installing-dependencies
addons:
  artifacts:
    s3_region: "eu-west-1"      # see https://docs.aws.amazon.com/general/latest/gr/rande.html
    debug: true
    paths:                      # - $(ls var/log/*.log | tr "\n" ":")
      #      - app/config
      - var/log
      - tests/_output/var/classes
      - phpstan-baseline.neon
  hosts:
    - pimcore-test.dev

# see https://docs.travis-ci.com/user/build-matrix/
jobs:
  allow_failures:
    # Run PHPStan level 3 without baseline, but allow them to fail
    - os: linux
      php: 7.4
      env:
        - TASK_TESTS=0
        - TASK_STAN=1
        - PHPSTAN_BASELINE=0
    - os: linux
      php: nightly
      env:
          - DATABASE_SERVER="mariadb-10.2"

  include:

    # All tests

    - name: "All Tests - PHP 7.4 | MariaDB 10.4"
      os: linux
      sudo: required
      php: 7.4
      env:
          - DATABASE_SERVER="mariadb-10.4"

    - name: "All Tests - PHP 7.4 | Percona 5.7"
      os: linux
      sudo: required
      php: 7.4
      env:
          - DATABASE_SERVER="percona-server-5.7"

    - name: "All Tests - PHP 8 | MariaDB 10.2"
      os: linux
      sudo: required
      php: nightly
      env:
          - DATABASE_SERVER="mariadb-10.2"

    - name: "All Tests - PHP 7.4 | MySQL 8.0 | Lowest dependencies"
      os: linux
      sudo: required
      php: 7.4
      env:
        - DATABASE_SERVER="mysql-8.0"
        - COMPOSER_PREFER_LOWEST=1

    # Test Stan - see https://github.com/phpstan/phpstan
    - name: "PHPStan - PHP 7.4 | Level 3 | baseline"
      os: linux
      php: 7.4
      env:
        - TASK_TESTS=0
        - TASK_STAN=1

    - name: "PHPStan - PHP 7.4 | Level 3 | baseline | Lowest dependencies"
      os: linux
      php: 7.4
      env:
        - TASK_TESTS=0
        - TASK_STAN=1
        - COMPOSER_PREFER_LOWEST=1

    - name: "PHPStan - PHP 7.4 | Level 3"
      os: linux
      php: 7.4
      env:
        - TASK_TESTS=0
        - TASK_STAN=1
        - PHPSTAN_BASELINE=0

    - name: "PHPStan - PHP 7.4 | Level 3 | Generate baseline"
      os: linux
      php: 7.4
      env:
        - TASK_TESTS=0
        - TASK_STAN=1
        - PHPSTAN_BASELINE_GENERATE=1

    # Test Docs
    - name: "Documentation"
      os: linux
      php: 7.4
      env:
        - TASK_TESTS=0
        - TASK_DOCS=1
      cache:
        directories:
          - tmp-docs/pimcore-docs/vendor
  fast_finish: true

cache:
  directories:
    - $HOME/.cache/composer

env:
  global:
    - COMPOSER_MEMORY_LIMIT=-1
    - COMPOSER_NO_INTERACTION=1
    - COMPOSER_PREFER_LOWEST=0
    - TASK_TESTS=1
    - TASK_STAN=0
    - TASK_DOCS=0
    - PHPSTAN_LEVEL=3
    - PHPSTAN_BASELINE=1
    - PHPSTAN_BASELINE_GENERATE=0
    - PIMCORE_ENVIRONMENT=test
    - PIMCORE_TEST=1
    - PIMCORE_TEST_URL=http://pimcore-test.dev
    - PIMCORE_TEST_DB_DSN="mysql://root@localhost/pimcore_test"
    - PIMCORE_TEST_REDIS_DSN="redis://localhost"
    - DATABASE_SERVER="mariadb-10.4"
    - PIMCORE_PROJECT_ROOT=$TRAVIS_BUILD_DIR

# see https://docs.travis-ci.com/user/job-lifecycle/
before_install:

# see https://docs.travis-ci.com/user/job-lifecycle/
install:
  - if [ $TASK_TESTS == 1 ]; then .travis/setup-tests.sh; fi
  - if [ $TASK_STAN == 1 ]; then .travis/setup-tests.sh; fi
  - if [ $TASK_DOCS == 1 ]; then .travis/setup-docs.sh; fi

# see https://docs.travis-ci.com/user/job-lifecycle/
before_script:
  - yes | pecl install imagick
  - phpenv config-rm xdebug.ini || true
  - if [ $TASK_TESTS == 1 ]; then .travis/setup-php.sh; fi
  - if [ $TASK_TESTS == 1 ]; then .travis/setup-functional-tests.sh; fi
  - if [ $TASK_STAN == 1 ]; then .travis/setup-php.sh; fi
  - mysql --version
  - mysql -e "CREATE DATABASE pimcore_test CHARSET=utf8mb4;"

# see https://docs.travis-ci.com/user/job-lifecycle/
script:
  - if [ $TASK_TESTS == 1 ]; then .travis/run-tests.sh; fi
  - if [ $TASK_DOCS == 1 ]; then .travis/run-docs.sh; fi
  - if [ $TASK_STAN == 1 ]; then .travis/run-stan.sh; fi
