# see https://docs.travis-ci.com/user/customizing-the-build/

notifications:
  email:
    - travis-ci@pimcore.org

branches:
  only:
    - master
    - /^v\d+\..*/

sudo: false
language: php

services:
  - redis

# see https://docs.travis-ci.com/user/installing-dependencies
addons:
  mariadb: '10.3'
  artifacts:
    s3_region: "eu-west-1"      # see https://docs.aws.amazon.com/general/latest/gr/rande.html
    debug: true
    paths:                      # - $(ls var/logs/*.log | tr "\n" ":")
      #      - app/config
      - var/logs
      - var/classes
  hosts:
    - pimcore-test.dev

# see https://docs.travis-ci.com/user/build-matrix/
jobs:
  allow_failures:
    # Run PHPStan level 2, but allow them to fail
    - os: linux
      php: 7.4
      env:
        - TASK_TESTS=0
        - TASK_STAN=1
        - PHPSTAN_LEVEL=2

  include:
    # Symfony 3.4 all tests
    - name: "All Tests - PHP 7.2 Symfony 3.4"
      os: linux
      sudo: required
      php: 7.2
      env:
        - SYMFONY_VERSION="^3.4"

    - name: "All Tests - PHP 7.3 Symfony 3.4"
      os: linux
      sudo: required
      php: 7.3
      env:
        - SYMFONY_VERSION="^3.4"

    # Symfony 4.* all tests
    - name: "All Tests - PHP 7.2 Symfony 4"
      os: linux
      sudo: required
      php: 7.2

    - name: "All Tests - PHP 7.3 Symfony 4"
      os: linux
      sudo: required
      php: 7.3

    - name: "All Tests - PHP 7.4 Symfony 4"
      os: linux
      sudo: required
      php: 7.4

    # Other Tests
    - name: "REST Tests - PHP 7.2 Symfony 3.4"
      os: linux
      sudo: required
      php: 7.2
      env:
        - SYMFONY_VERSION="^3.4"
        - PIMCORE_TEST_SUITE=rest
        - PIMCORE_TEST_ENV=http

    - name: "REST Tests - PHP 7.3 Symfony 3.4"
      os: linux
      sudo: required
      php: 7.3
      env:
        - SYMFONY_VERSION="^3.4"
        - PIMCORE_TEST_SUITE=rest
        - PIMCORE_TEST_ENV=http

    # Test Stan - see https://github.com/phpstan/phpstan
    - name: "PHPStan Level 1 - PHP 7.2 Symfony 3.4"
      os: linux
      php: 7.2
      env:
        - SYMFONY_VERSION="^3.4"
        - TASK_TESTS=0
        - TASK_STAN=1
    - name: "PHPStan Level 1 - PHP 7.3 Symfony 3.4"
      os: linux
      php: 7.3
      env:
        - SYMFONY_VERSION="^3.4"
        - TASK_TESTS=0
        - TASK_STAN=1

    # Test Stan Symfony ^4.0
    - name: "PHPStan Level 1 - PHP 7.2 Symfony 4"
      os: linux
      php: 7.2
      env:
        - TASK_TESTS=0
        - TASK_STAN=1

    - name: "PHPStan Level 1 - PHP 7.3 Symfony 4"
      os: linux
      php: 7.3
      env:
        - TASK_TESTS=0
        - TASK_STAN=1

    - name: "PHPStan Level 2 - PHP 7.4 Symfony 4"
      os: linux
      php: 7.4
      env:
        - TASK_TESTS=0
        - TASK_STAN=1
        - PHPSTAN_LEVEL=2

    # Test Docs
    - name: "Documentation"
      os: linux
      php: 7.2
      env:
        - TASK_TESTS=0
        - TASK_DOCS=1
      cache:
        directories:
          - tmp-docs/pimcore-docs/vendor
  fast_finish: true

cache:
  directories:
    - $HOME/.cache/composer

env:
  global:
    - COMPOSER_MEMORY_LIMIT=-1
    - TASK_TESTS=1
    - TASK_STAN=0
    - TASK_DOCS=0
    - PHPSTAN_LEVEL=1
    - PIMCORE_ENVIRONMENT=test
    - PIMCORE_TEST=1
    - PIMCORE_TEST_URL=http://pimcore-test.dev
    - PIMCORE_TEST_DB_DSN="mysql://root@localhost/pimcore_test"
    - PIMCORE_TEST_CACHE_REDIS_DATABASE=1
    - SYMFONY_VERSION=^4.0
    - PIMCORE_PROJECT_ROOT=$TRAVIS_BUILD_DIR
    - PIMCORE_PHP_ERROR_REPORTING=32767 # E_ALL

# see https://docs.travis-ci.com/user/job-lifecycle/
before_install:
  - mysql --version
  - mysql -e "CREATE DATABASE pimcore_test CHARSET=utf8mb4;"

# see https://docs.travis-ci.com/user/job-lifecycle/
install:
  - if [ $TASK_TESTS == 1 ]; then .travis/setup-tests.sh; fi
  - if [ $TASK_STAN == 1 ]; then .travis/setup-tests.sh; fi
  - if [ $TASK_DOCS == 1 ]; then .travis/setup-docs.sh; fi

# see https://docs.travis-ci.com/user/job-lifecycle/
before_script:
  - yes | pecl install imagick
  - phpenv config-rm xdebug.ini || true
  - if [ $TASK_TESTS == 1 ]; then .travis/setup-php.sh; fi
  - if [ $TASK_TESTS == 1 ]; then .travis/setup-functional-tests.sh; fi
  - if [ $TASK_STAN == 1 ]; then .travis/setup-php.sh; fi

# see https://docs.travis-ci.com/user/job-lifecycle/
script:
  - if [ $TASK_TESTS == 1 ]; then .travis/run-tests.sh; fi
  - if [ $TASK_DOCS == 1 ]; then .travis/run-docs.sh; fi
  - if [ $TASK_STAN == 1 ]; then .travis/run-stan.sh; fi
