notifications:
  email:
    - travis-ci@pimcore.org

sudo: required
language: php

php:
  - 5.6.29
  - 7
  - 7.1

addons:
  hosts:
    - pimcore-test.dev

env:
  global:
    - TASK_TESTS=1
    - TASK_DOCS=0

matrix:
  include:
    - os: linux
      sudo: false
      php: 7.1
      services: ~
      addons: ~
      env:
        - TASK_TESTS=0
        - TASK_DOCS=1

install:
  - if [ $TASK_TESTS == 1 ]; then chmod +x .travis/setup-sudo.sh && .travis/setup-sudo.sh; fi
  - if [ $TASK_TESTS == 1 ]; then composer install; fi
  - if [ $TASK_DOCS == 1 ]; then .ci/setup-docs.sh; fi

script:
  - if [ $TASK_TESTS == 1 ]; then (cd tests && chmod +x alltests.sh && ./alltests.sh); fi
  - if [ $TASK_DOCS == 1 ]; then .ci/run-docs.sh; fi

after_script:
  - if [ $TASK_TESTS == 1 ]; then cat $TRAVIS_BUILD_DIR/tests/tmp/var/log/debug.log; fi
  - if [ $TASK_TESTS == 1 ]; then cat $TRAVIS_BUILD_DIR/tests/tmp/var/log/php.log; fi
  - if [ $TASK_TESTS == 1 ]; then cat $TRAVIS_BUILD_DIR/apache-error.log; fi
  - if [ $TASK_TESTS == 1 ]; then cat $TRAVIS_BUILD_DIR/apache-access.log; fi
