services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    #
    # CHECKOUT MANAGER
    #
    # Predefined core checkout manager implementations. Undefined arguments (order manager, commit order processor,
    # options, payment manager, ...) will be set from config.
    #

    Pimcore\Bundle\EcommerceFrameworkBundle\CheckoutManager\CheckoutManagerFactory:
        arguments:
            - '@pimcore_ecommerce.environment'
            - '@pimcore_ecommerce.locator.order_manager'
            - '@pimcore_ecommerce.locator.checkout_manager.commit_order_processor'
            - [] # checkout steps
            - '@?' # payment provider
            - [] # options

    Pimcore\Bundle\EcommerceFrameworkBundle\CheckoutManager\CommitOrderProcessor:
        arguments:
            - '@pimcore_ecommerce.locator.order_manager'
            - [] # options
