services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    Pimcore\Bundle\EcommerceFrameworkBundle\OrderManager\Order\AgentFactory:
        arguments:
            - '@pimcore_ecommerce.environment'
            - '@pimcore_ecommerce.payment_manager'
            - []

    Pimcore\Bundle\EcommerceFrameworkBundle\OrderManager\OrderManager:
        arguments:
            - '@pimcore_ecommerce.environment'
            - '@?'
            - '@pimcore_ecommerce.voucher_service'
            - []


    Pimcore\Bundle\EcommerceFrameworkBundle\OrderManager\V7\OrderManager:
        arguments:
            - '@pimcore_ecommerce.environment'
            - '@?'
            - '@pimcore_ecommerce.voucher_service'
            - []