services:
    Pimcore\Bundle\CoreBundle\Command\OptimizeImageThumbnailsCommand:
        arguments:
            - '@Pimcore\Image\Optimizer'
        tags:
            - { name: console.command, command: 'pimcore:thumbnails:optimize-images' }

    Pimcore\Bundle\CoreBundle\Command\MaintenanceCommand:
        arguments:
            - '@Pimcore\Maintenance\Executor'
            - '@logger'
        tags:
            - { name: console.command, command: 'pimcore:maintenance' }
