services:
    Pimcore\Bundle\CoreBundle\Command\ThumbnailsOptimizeImagesCommand:
        arguments:
            - '@Pimcore\Image\Optimizer'
        tags:
            - { name: console.command, command: 'pimcore:thumbnails:optimize-images' }