services:
    Pimcore\Image\Optimizer:
        public: true

    Pimcore\Image\Optimizer\AdvancedPngOptimizer:

    Pimcore\Image\Optimizer\CjpegOptimizer:

    Pimcore\Image\Optimizer\JpegoptimOptimizer:

    Pimcore\Image\Optimizer\PngCrushOptimizer:

    Pimcore\Image\Optimizer\PngOutOptimizer:

    Pimcore\Image\Optimizer\ZopflipngOptimizer:

    Pimcore\Image\Optimizer\SpatieImageOptimizer:
        tags:
            - { name: pimcore.image.optimizer }