services:
    _defaults:
        autowire: true
        autoconfigure: true

    #
    # TRANSLATOR
    #

    Pimcore\Translation\Translator:
        decorates: translator
        arguments:
            - '@Pimcore\Translation\Translator.inner'
        calls:
            - [setKernel, ['@kernel']]
            - [setAdminPath, ['%pimcore.admin.translations.path%']]

    #
    # LOCALE
    #

    Pimcore\Localization\LocaleService:
        arguments:
            # TODO can we just type hint against TranslatorInterface and use autowiring here or do we need to call
            # this on the pimcore.translator?
            $translator: '@Pimcore\Translation\Translator'

    # formatting service for dates, times and numbers
    Pimcore\Localization\IntlFormatter: ~
