services:
    _defaults:
        autowire: true
        autoconfigure: true

    Pimcore\Maintenance\Executor:
        arguments:
            - 'maintenance.pid'
            - '@logger'
            - '@Symfony\Component\Lock\LockFactory'
            - '@messenger.bus.pimcore-core'

    Pimcore\Maintenance\Tasks\ScheduledTasksTask:
        arguments:
            - '@logger'
        tags:
            - { name: pimcore.maintenance.task, type: scheduledtasks }

    Pimcore\Maintenance\Tasks\LogMailMaintenanceTask:
        arguments:
            - '@doctrine.dbal.default_connection'
        tags:
            - { name: pimcore.maintenance.task, type: logmaintenance }

    Pimcore\Maintenance\Tasks\LogCleanupTask:
        tags:
            - { name: pimcore.maintenance.task, type: cleanuplogfiles }

    Pimcore\Maintenance\Tasks\LogErrorCleanupTask:
        arguments:
            - '@doctrine.dbal.default_connection'
        tags:
            - { name: pimcore.maintenance.task, type: httperrorlog }

    Pimcore\Maintenance\Tasks\LogArchiveTask:
        arguments:
            - '@doctrine.dbal.default_connection'
        tags:
            - { name: pimcore.maintenance.task, type: archiveLogEntries }

    Pimcore\Maintenance\Tasks\CleanupBrickTablesTask:
        arguments:
            - '@logger'
        tags:
            - { name: pimcore.maintenance.task, type: cleanupBrickTables }

    Pimcore\Maintenance\Tasks\CleanupClassificationstoreTablesTask:
        arguments:
            - '@logger'
        tags:
            - { name: pimcore.maintenance.task, type: cleanupClassificationstoreTables }

    Pimcore\Maintenance\Tasks\CleanupFieldcollectionTablesTask:
        arguments:
            - '@logger'
        tags:
            - { name: pimcore.maintenance.task, type: cleanupFieldcollectionTables }

    Pimcore\Maintenance\Tasks\VersionsCleanupTask:
        arguments:
            - '@logger'
        tags:
            - { name: pimcore.maintenance.task, type: versioncleanup }

    Pimcore\Maintenance\Tasks\VersionsCleanupStackTraceDbTask:
        arguments:
            - '@logger'
        tags:
            - { name: pimcore.maintenance.task, type: VersionsCleanupStackTraceDb }

    Pimcore\Maintenance\Tasks\RedirectCleanupTask:
        arguments:
            - '@logger'
        tags:
            - { name: pimcore.maintenance.task, type: redirectcleanup }

    Pimcore\Maintenance\Tasks\DbCleanupBrokenViewsTask:
        arguments:
            - '@doctrine.dbal.default_connection'
            - '@logger'
        tags:
            - { name: pimcore.maintenance.task, type: cleanupbrokenviews }

    Pimcore\Maintenance\Tasks\TmpStoreCleanupTask:
        arguments:
            - '@doctrine.dbal.default_connection'
        tags:
            - { name: pimcore.maintenance.task, type: tmpstorecleanup }


    Pimcore\Maintenance\Tasks\HousekeepingTask:
        arguments:
            - '%pimcore.maintenance.housekeeping.cleanup_tmp_files_atime_older_than%'
            - '%pimcore.maintenance.housekeeping.cleanup_profiler_files_atime_older_than%'
        tags:
            - { name: pimcore.maintenance.task, type: housekeeping }

    Pimcore\Maintenance\Tasks\LowQualityImagePreviewTask:
        arguments:
            - '@logger'
        tags:
            - { name: pimcore.maintenance.task, type: low_quality_image_preview }

    Pimcore\Maintenance\Tasks\StaticPagesGenerationTask:
        arguments:
            - '@Pimcore\Document\StaticPageGenerator'
            - '@logger'
        tags:
            - { name: pimcore.maintenance.task, type: documents_static_page_generate }

    Pimcore\Maintenance\Tasks\FullTextIndexOptimizeTask:
        tags:
            - { name: pimcore.maintenance.task, type: optimize_fulltext_indexes }
