services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pimcore\Migrations\Command\:
        resource: '../../../../Migrations/Command'

    Pimcore\Migrations\Configuration\ConfigurationFactory:
        public: true

    Pimcore\Migrations\MigrationManager: ~
