services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pimcore\Migrations\FilteredMigrationsRepository:
        public: true

    Pimcore\Migrations\FilteredTableMetadataStorage:
        public: true

