services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pimcore\Migrations\Command\:
        deprecated: 'The "%service_id%" service is deprecated and will be removed in Pimcore v7. Use Doctrine Migrations commands instead.'
        resource: '../../../../lib/Migrations/Command'

    Pimcore\Migrations\Configuration\ConfigurationFactory:
        deprecated: 'The "%service_id%" service is deprecated and will be removed in Pimcore v7.'
        public: true

    Pimcore\Migrations\MigrationManager:
        deprecated: 'The "%service_id%" service is deprecated and will be removed in Pimcore v7.'
        lazy: true
        public: true
