services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pimcore\Migrations\Command\:
        resource: '../../../../lib/Migrations/Command'

    Pimcore\Migrations\Configuration\ConfigurationFactory:
        public: true

    Pimcore\Migrations\MigrationManager:
        public: true
