services:
    _defaults:
        autowire: true
        autoconfigure: true

    # public alias to PHP engine
    pimcore.templating.engine.php:
        alias: templating.engine.php
        public: true
        deprecated: 'The "%alias_id%" service is deprecated. Use Twig instead.'
