imports:
    - { resource: security.yml }

pimcore:
    # we override the generated user model with a custom class which implements the UserInterface
    models:
        class_overrides:
            'Pimcore\Model\DataObject\User': 'AppBundle\Model\DataObject\User'

    sitemaps:
        generators:
            app_news: AppBundle\Sitemaps\NewsGenerator
