pimcore_admin:
    user:
        default_key_bindings:
            quick_search:
                key: 'F'
                action: quickSearch
                ctrl: true
                shift: true

framework:
    messenger:
        transports:
            pimcore_search_backend_message: "doctrine://default?queue_name=pimcore_search_backend_message"
        routing:
            Pimcore\Bundle\SimpleBackendSearchBundle\Message\SearchBackendMessage: pimcore_search_backend_message