blank_issues_enabled: false
contact_links:
    - name: Community Support
      url: https://github.com/pimcore/pimcore/discussions
      about: Please ask and answer questions here.
    - name: Security Issue Report
      url: https://pimcorehq.wufoo.com/forms/pimcore-security-report/
      about: Please report security vulnerabilities here.