name: Feature Request
description: Request or propose a feature or improvement
title: "[Feature]: "
labels: ["New Feature"]
body:
    - type: markdown
      attributes:
          value: |
              ## Important notice
              As an open source project we love to work together with our community to improve and develop our products.
              It's also important for us to make clear that **we're not working for you or your company**,
              but we enjoy to work together to improve or add new features to the product.
              So we would love to [discuss features and improvements first](https://github.com/pimcore/pimcore/discussions),
              and once there is a PR ready, we also take the time to review and merge it into the project.
              For details see also our [contributing guidelines](https://github.com/pimcore/pimcore/blob/10.x/CONTRIBUTING.md).

              Feature requests that do not meet the conditions listed below will be closed/deleted without comment.

              - There's no existing ticket for the same topic
              - This is already a specific ready-to-work-on feature request
              - Discussions should take place [here first](https://github.com/pimcore/pimcore/discussions).

    - type: textarea
      attributes:
          label: Feature description
      validations:
          required: true
