services:
    Pimcore\Messenger\Handler\SendNewsletterHandler:
        arguments:
            - '%pimcore.config%'
            - '@pimcore.newsletter.address_source_adapter.factories'
        tags:
            - { name: messenger.message_handler }

    Pimcore\Messenger\Handler\VideoConvertHandler:
        tags:
            - { name: messenger.message_handler }

    Pimcore\Messenger\Handler\CleanupThumbnailsHandler:
        tags:
            - { name: messenger.message_handler }

    Pimcore\Messenger\Handler\AssetUpdateTasksHandler:
        arguments:
            - '@logger'
        tags:
            - { name: messenger.message_handler }

    Pimcore\Messenger\Handler\AssetPreviewImageHandler:
        arguments:
            - '@logger'
        tags:
            - { name: messenger.message_handler }

    Pimcore\Messenger\Handler\MaintenanceTaskHandler:
        arguments:
            - '@Pimcore\Maintenance\Executor'
        tags:
            - { name: messenger.message_handler }

    Pimcore\Messenger\Handler\SearchBackendHandler:
        tags:
            - { name: messenger.message_handler }

    Pimcore\Messenger\Handler\OptimizeImageHandler:
        arguments:
            - '@Pimcore\Image\Optimizer'
            - '@logger'
        tags:
            - { name: messenger.message_handler }

    Pimcore\Messenger\Handler\GeneratePagePreviewHandler:
        arguments:
            - '@logger'
        tags:
            - { name: messenger.message_handler }

    Pimcore\Messenger\Handler\GenerateWeb2PrintPdfHandler:
        arguments:
            - '@logger'
        tags:
            - { name: messenger.message_handler }

    Pimcore\Messenger\Handler\VersionDeleteHandler:
        tags:
            - { name: messenger.message_handler }

    Pimcore\Messenger\Handler\SanityCheckHandler:
        tags:
            - { name: messenger.message_handler }
