services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    Pimcore\Bundle\EcommerceFrameworkBundle\Tracking\TrackingManager: ~
    Pimcore\Bundle\EcommerceFrameworkBundle\Tracking\TrackingItemBuilder: ~

    #
    # TRACKERS
    #
    # Predefined core trackers. The item builder can be overwritten via config (see extension).
    #

    Pimcore\Bundle\EcommerceFrameworkBundle\Tracking\Tracker\Analytics\EnhancedEcommerce:
        arguments:
            $trackingItemBuilder: '@Pimcore\Bundle\EcommerceFrameworkBundle\Tracking\TrackingItemBuilder'

    Pimcore\Bundle\EcommerceFrameworkBundle\Tracking\Tracker\Analytics\Ecommerce:
        arguments:
            $trackingItemBuilder: '@Pimcore\Bundle\EcommerceFrameworkBundle\Tracking\TrackingItemBuilder'

    Pimcore\Bundle\EcommerceFrameworkBundle\Tracking\Tracker\Analytics\UniversalEcommerce:
        arguments:
            $trackingItemBuilder: '@Pimcore\Bundle\EcommerceFrameworkBundle\Tracking\TrackingItemBuilder'

    Pimcore\Bundle\EcommerceFrameworkBundle\Tracking\Tracker\GoogleTagManager:
        arguments:
            $trackingItemBuilder: '@Pimcore\Bundle\EcommerceFrameworkBundle\Tracking\TrackingItemBuilder'

    #
    # GOOGLE TAG MANAGER
    #

    Pimcore\Analytics\GoogleTagManager\EventSubscriber\TrackingCodeSubscriber: ~