services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pimcore\Bundle\EcommerceFrameworkBundle\EventListener\IndexUpdateListener:
        tags:
            - { name: monolog.logger, channel: pimcore_ecommerce_indexupdater }

    Pimcore\Bundle\EcommerceFrameworkBundle\EventListener\Frontend\TrackingCodeFlashMessageListener: ~
    Pimcore\Bundle\EcommerceFrameworkBundle\EventListener\SessionBagListener: ~
