services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pimcore\Targeting\Session\SessionConfigurator:
        deprecated:
            message: 'The "%service_id%" service is deprecated, use TargetingSessionBagListener instead.'
            package: pimcore/pimcore
            version: 10.5
