
name: "POEditor Translations Import"

on:
    workflow_dispatch:
        inputs:
            languages:
                description: 'Language-Codes (csv, eg. zh-CN)'
                required: false
                default: ''


permissions:
  contents: read

jobs:
    poeditor:
        permissions:
          contents: write  # for stefanzweifel/git-auto-commit-action to push code in repo
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - name: "Install PHP"
              uses: "shivammathur/setup-php@v2"

            - name: POEditor
              env:
                  POEDITOR_TOKEN: ${{ secrets.POEDITOR_TOKEN }}
                  POEDITOR_LANGUAGES: ${{ github.event.inputs.languages }}
              run: |
                  php .github/ci/scripts/poeditor-import.php

            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: Update POEditor translations