
name: "Psalm Static Analysis"

on:
    pull_request:
        branches:
            - "[0-9]+.[0-9]+"
            - "[0-9]+.x"
    push:
        branches:
            - "[0-9]+.[0-9]+"
            - "[0-9]+.x"
            - "*_actions"

jobs:
    psalm:
        name: Psalm
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Psalm
              uses: docker://vimeo/psalm-github-actions
              with:
                security_analysis: true
                composer_ignore_platform_reqs: true