framework:
    messenger:
        routing:
            'Pimcore\Bundle\WebToPrintBundle\Messenger\GenerateWeb2PrintPdfMessage': pimcore_core
pimcore:
    documents:
        type_definitions:
            map:
                printpage: Pimcore\Bundle\WebToPrintBundle\Model\Document\Printpage
                printcontainer: Pimcore\Bundle\WebToPrintBundle\Model\Document\Printcontainer

    routing:
        direct_route_document_types: ['printpage', 'printcontainer']